# Site settings
title: Actlist
#email: your-email@domain.com
description: >
  Easy and simply execute your own act list

logo: /img/og-img-1200x630.png
#also head.html has too.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://actlist.silentsoft.org
#url: http://actlist.silentsoft.org # the base hostname & protocol for your site
git_address: https://github.com/silentsoft/actlist
git_edit_address: https://github.com/silentsoft/actlist.silentsoft.org/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
#bootwatch: paper
bootwatch: actlist

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .idea/
  - actlist.silentsoft.org.iml
  - .gitignore
  - README.md

timezone: Asia/Seoul
future: true

google_site_verification: L-7RmNNelAFzLK3MPycWRN0o7Q9DxceTOVJFOCD22kg

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  plugins:
    permalink: /:collection/:path/
    output: true
  archives:
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      sectionid: docs
    seo:
      type: "WebPage"
  - scope:
      path: _plugins
      type: plugins
    values:
      layout: plugin
      sectionid: plugins
  - scope:
      path: _archives
      type: archives
    values:
      layout: archives
      sectionid: archives
  - scope:
      path: "410.html"
    values:
      sitemap: false
