# Site settings
title: Actlist
#email: your-email@domain.com
description: >
  Execute your own action list easily and simply

logo: /img/og-img-1200x630.png
#also head.html has too.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://actlist.io
docs_url: https://docs.actlist.io
git_address: https://github.com/actlist
#git_edit_address: https://github.com/actlist/actlist.io/blob/master
#git_history_address: https://github.com/actlist/actlist.io/commits/master

download_api: /api/download?url=
download_statistics_api: /api/download?uuid=$uuid&url=

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
#bootwatch: paper
bootwatch: actlist

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .idea/
  - actlist.silentsoft.org.iml
  - .gitignore
  - README.md

timezone: Asia/Seoul
future: true

google_site_verification: L-7RmNNelAFzLK3MPycWRN0o7Q9DxceTOVJFOCD22kg
google_analytics: UA-121310823-2

collections:
#  docs:
#    permalink: /:collection/:path/
#    output: true
  plugins:
    permalink: /:collection/:path/
    output: true
  archives:
    output: true

defaults:
#  - scope:
#      path: _docs
#      type: docs
#    values:
#      layout: docs
#      sectionid: docs
#    seo:
#      type: "WebPage"
  - scope:
      path: _plugins
      type: plugins
    values:
      layout: plugin
      sectionid: plugins
  - scope:
      path: _archives
      type: archives
    values:
      layout: archives
      sectionid: archives
  - scope:
      path: "410.html"
    values:
      sitemap: false
